# Generated by Django 5.2.3 on 2025-06-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=200, verbose_name='نام آزمایشگاه')),
                ('lab_phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره آزمایشگاه')),
                ('lab_mobile_number', models.CharField(max_length=20, verbose_name='موبایل آزمایشگاه')),
                ('lab_address', models.TextField(verbose_name='آدرس آزمایشگاه')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیدی تلگرام')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=100, verbose_name='شماره پرونده')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('client_name', models.CharField(max_length=200, verbose_name='نام کارفرما')),
                ('client_phone_number', models.CharField(max_length=20, verbose_name='شماره تماس کارفرما')),
                ('supervisor_name', models.CharField(max_length=200, verbose_name='نام ناظر')),
                ('supervisor_phone_number', models.CharField(max_length=20, verbose_name='شماره تماس ناظر')),
                ('requester_name', models.CharField(max_length=200, verbose_name='نام درخواست دهنده')),
                ('requester_phone_number', models.CharField(max_length=20, verbose_name='شماره تماس درخواست دهنده')),
                ('municipality_zone', models.CharField(max_length=100, verbose_name='منطقه شهرداری')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('project_usage_type', models.CharField(max_length=100, verbose_name='کاربری پروژه')),
                ('floor_count', models.IntegerField(verbose_name='طبقات')),
                ('cement_type', models.CharField(max_length=100, verbose_name='نوع سیمان')),
                ('occupied_area', models.FloatField(verbose_name='سطح زیربنا اشغال شده')),
                ('mold_type', models.CharField(max_length=100, verbose_name='نوع قالب')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('test_type', models.CharField(max_length=100, verbose_name='نوع آزمون')),
                ('sampling_volume', models.CharField(max_length=50, verbose_name='حجم نمونه برداری')),
                ('cement_grade', models.CharField(max_length=50, verbose_name='عیار سیمان')),
                ('category', models.CharField(max_length=100, verbose_name='رده')),
                ('weather_condition', models.CharField(max_length=100, verbose_name='وضعیت جوی')),
                ('concrete_factory', models.CharField(max_length=200, verbose_name='کارخانه بتن')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concrete_temperature', models.FloatField(verbose_name='دمای بتن')),
                ('ambient_temperature', models.FloatField(verbose_name='دمای محیط')),
                ('slump', models.FloatField()),
                ('range', models.CharField(max_length=50, verbose_name='محدوده')),
                ('air_percentage', models.FloatField(verbose_name='درصد هوا')),
                ('has_additive', models.BooleanField(default=False, verbose_name='داشتن افزودنی')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.sample')),
            ],
            options={
                'verbose_name_plural': 'Sampling Series',
            },
        ),
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_in_days', models.IntegerField(verbose_name='چند روزه')),
                ('mass', models.FloatField(verbose_name='جرم')),
                ('breaking_load', models.FloatField(verbose_name='بار گسیختگی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شدن')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('deadline', models.DateTimeField(verbose_name='زمان ددلاین')),
                ('sample_identifier', models.CharField(max_length=100, verbose_name='نمونه قالب')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='دیتا اضافی')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='api.samplingseries')),
            ],
        ),
    ]
