# Generated by Django 5.2.3 on 2025-06-14 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_address_alter_project_cement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='مبلغ کل قرارداد'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت پروژه'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'واریزی'), ('expense', 'هزینه/برداشت')], max_length=7, verbose_name='نوع تراکنش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ')),
                ('date', models.DateTimeField(verbose_name='تاریخ تراکنش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.project', verbose_name='پروژه')),
            ],
        ),
    ]







