# Generated by Django 5.2.3 on 2025-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ticket_ticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mold',
            name='age_in_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mold',
            name='breaking_load',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='mold',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mold',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mold',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mold',
            name='mass',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='mold',
            name='sample_identifier',
            field=models.CharField(max_length=100),
        ),
    ]
