# Generated by Django 5.2.3 on 2025-10-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mold_age_in_days_alter_mold_breaking_load_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cement_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mold_type',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='samplingseries',
            name='air_percentage',
        ),
        migrations.RemoveField(
            model_name='samplingseries',
            name='ambient_temperature',
        ),
        migrations.RemoveField(
            model_name='samplingseries',
            name='range',
        ),
        migrations.AddField(
            model_name='mold',
            name='post_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/post_break/', verbose_name='عکس بعد شکست'),
        ),
        migrations.AddField(
            model_name='mold',
            name='pre_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/pre_break/', verbose_name='عکس قبل شکست'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_type',
            field=models.CharField(choices=[('compressive', 'مقاومت فشاری'), ('schmidt', 'چکش اشمیت')], default='compressive', max_length=20, verbose_name='نوع آزمون'),
        ),
        migrations.AddField(
            model_name='sample',
            name='ambient_temperature',
            field=models.FloatField(default=20.0, verbose_name='دمای محیط'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cement_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='تیپ سیمان'),
        ),
        migrations.AddField(
            model_name='sample',
            name='concrete_production_method',
            field=models.CharField(choices=[('factory_batching', 'بچینگ کارخانه'), ('manual', 'دستی')], default='factory_batching', max_length=20, verbose_name='روش ساخت بتن'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sampling_location',
            field=models.CharField(default='', max_length=200, verbose_name='محل نمونه\u200cبرداری'),
        ),
        migrations.AddField(
            model_name='sample',
            name='specimen_size',
            field=models.CharField(choices=[('cube_15', '15x15x15 cm'), ('cyl_300_150', 'ارتفاع 300mm - قطر 150mm'), ('cyl_200_100', 'ارتفاع 200mm - قطر 100mm')], default='cube_15', max_length=20, verbose_name='سایز نمونه'),
        ),
        migrations.AddField(
            model_name='sample',
            name='specimen_type',
            field=models.CharField(choices=[('cube', 'مکعبی'), ('cylinder', 'استوانه\u200cای')], default='cube', max_length=10, verbose_name='نوع نمونه'),
        ),
        migrations.AddField(
            model_name='samplingseries',
            name='axis',
            field=models.CharField(blank=True, max_length=100, verbose_name='محور'),
        ),
        migrations.AddField(
            model_name='samplingseries',
            name='concrete_temperature_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/concrete_temperature/'),
        ),
        migrations.AddField(
            model_name='samplingseries',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام سری'),
        ),
        migrations.AddField(
            model_name='samplingseries',
            name='slump_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/slump/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='نام کارفرما'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس کارفرما'),
        ),
        migrations.AlterField(
            model_name='project',
            name='floor_count',
            field=models.IntegerField(verbose_name='طبقات'),
        ),
        migrations.AlterField(
            model_name='project',
            name='municipality_zone',
            field=models.CharField(max_length=100, verbose_name='منطقه شهرداری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='occupied_area',
            field=models.FloatField(verbose_name='سطح زیربنا اشغال شده (مترمربع)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_usage_type',
            field=models.CharField(max_length=100, verbose_name='کاربری پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requester_name',
            field=models.CharField(max_length=200, verbose_name='نام درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requester_phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس درخواست دهنده'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_name',
            field=models.CharField(max_length=200, verbose_name='نام ناظر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_phone_number',
            field=models.CharField(max_length=20, verbose_name='شماره تماس ناظر'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampling_volume',
            field=models.FloatField(verbose_name='حجم بتن\u200cریزی (متر مکعب)'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='slump',
            field=models.FloatField(verbose_name='اسلامپ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد'),
        ),
        migrations.CreateModel(
            name='SamplingSeriesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='series/specimens/', verbose_name='عکس نمونه\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.samplingseries', verbose_name='سری نمونه')),
            ],
        ),
    ]
