# Generated by Django 6.0.7 on 2026-07-25 17:32

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_cement_type_remove_project_mold_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labprofile',
            options={'verbose_name': 'پروفایل آزمایشگاه', 'verbose_name_plural': 'پروفایل\u200cهای آزمایشگاه'},
        ),
        migrations.AlterModelOptions(
            name='mold',
            options={'ordering': ['deadline'], 'verbose_name': 'قالب', 'verbose_name_plural': 'قالب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-date'], 'verbose_name': 'نمونه', 'verbose_name_plural': 'نمونه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='samplingseries',
            options={'ordering': ['id'], 'verbose_name': 'سری نمونه', 'verbose_name_plural': 'سری\u200cهای نمونه'},
        ),
        migrations.AlterModelOptions(
            name='samplingseriesphoto',
            options={'ordering': ['created_at'], 'verbose_name': 'عکس سری نمونه', 'verbose_name_plural': 'عکس\u200cهای سری نمونه'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'پیام تیکت', 'verbose_name_plural': 'پیام\u200cهای تیکت'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AlterField(
            model_name='mold',
            name='post_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/post_break/', validators=[api.validators.validate_image_file], verbose_name='عکس بعد شکست'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='pre_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/pre_break/', validators=[api.validators.validate_image_file], verbose_name='عکس قبل شکست'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_number',
            field=models.CharField(db_index=True, max_length=100, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='ambient_temperature',
            field=models.FloatField(default=25.0, verbose_name='دمای محیط'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='concrete_temperature_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/concrete_temperature/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='slump_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/slump/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='samplingseriesphoto',
            name='image',
            field=models.ImageField(upload_to='series/specimens/', validators=[api.validators.validate_image_file], verbose_name='عکس نمونه\u200cها'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['series', 'age_in_days'], name='api_mold_series__50e5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-created_at'], name='api_project_owner_i_6b1a73_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['project', 'date'], name='api_sample_project_a5fc11_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', 'type', 'date'], name='api_transac_project_6e4444_idx'),
        ),
    ]
