# Generated by Django 5.2.16 on 2026-08-03 10:48

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_labprofile_options_alter_mold_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام معیار')),
                ('standard_name', models.CharField(blank=True, max_length=200, verbose_name='استاندارد')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='پارامترها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'معیار پذیرش',
                'verbose_name_plural': 'معیارهای پذیرش',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CuringTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مخزن')),
                ('name', models.CharField(max_length=200, verbose_name='نام مخزن')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='ظرفیت')),
                ('water_temperature', models.FloatField(blank=True, null=True, verbose_name='دمای آب (°C)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='موقعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مخزن عمل\u200cآوری',
                'verbose_name_plural': 'مخزن\u200cهای عمل\u200cآوری',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره درخواست')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='مهلت')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('comments', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست آزمایشگاهی',
                'verbose_name_plural': 'درخواست\u200cهای آزمایشگاهی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('calibration', 'کالیبراسیون'), ('maintenance', 'نگهداری'), ('repair', 'تعمیر')], default='maintenance', max_length=20, verbose_name='نوع')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='نوبت بعدی')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'رکورد نگهداری',
                'verbose_name_plural': 'رکوردهای نگهداری',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(choices=[('sample_ready', 'آمادگی نمونه'), ('late_test', 'تأخیر آزمون'), ('equipment_calibration', 'کالیبراسیون دستگاه'), ('report_approved', 'تأیید گزارش'), ('report_reviewed', 'بازبینی گزارش'), ('project_update', 'بروزرسانی پروژه'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='نوع')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(blank=True, verbose_name='متن')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدیر سیستم'), ('lab_manager', 'مدیر آزمایشگاه'), ('quality_manager', 'مدیر کنترل کیفیت'), ('engineer', 'مهندس'), ('technician', 'تکنسین'), ('reception', 'پذیرش'), ('client', 'مشتری'), ('readonly', 'فقط\u200cخواندنی'), ('factory_manager', 'مدیر کارخانه'), ('supervisor', 'ناظر')], default='client', max_length=20, verbose_name='نقش')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='شماره گزارش')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('reviewed', 'بازبینی شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='محتوای گزارش')),
                ('qr_verify_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='توکن تائید QR')),
                ('digital_signature', models.JSONField(blank=True, default=dict, verbose_name='امضای دیجیتال')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بازبینی')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='نسخه')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='محتوای نسخه')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='توضیح تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نسخه گزارش',
                'verbose_name_plural': 'نسخه\u200cهای گزارش',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع نمونه',
                'verbose_name_plural': 'انواع نمونه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='دمای محیط (°C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='رطوبت (%)')),
                ('measured_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر اندازه\u200cگیری')),
                ('calculated_values', models.JSONField(blank=True, default=dict, verbose_name='مقادیر محاسباتی')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='نتیجه نهایی')),
                ('result_status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت نتیجه')),
                ('status', models.CharField(choices=[('planned', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده')], db_index=True, default='planned', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اجرای آزمون',
                'verbose_name_plural': 'اجرای آزمون\u200cها',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد آزمون')),
                ('name', models.CharField(max_length=200, verbose_name='نام آزمون')),
                ('category', models.CharField(choices=[('concrete', 'بتن'), ('cement', 'سیمان'), ('aggregate', 'مصالح سنگی'), ('water', 'آب'), ('soil', 'خاک'), ('steel', 'فولاد'), ('asphalt', 'آسفالت'), ('general', 'عمومی')], default='concrete', max_length=20, verbose_name='دسته')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='واحد')),
                ('method_reference', models.CharField(blank=True, max_length=200, verbose_name='مرجع روش آزمون')),
                ('params_schema', models.JSONField(blank=True, default=list, verbose_name='پارامترهای اندازه\u200cگیری')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع آزمون',
                'verbose_name_plural': 'انواع آزمون',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='labprofile',
            name='lab_code',
            field=models.CharField(blank=True, help_text='کد اختصاصی برای پیوستن اپراتور/تکنسین\u200cها به آزمایشگاه', max_length=16, unique=True, verbose_name='کد عضویت آزمایشگاه'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to=settings.AUTH_USER_MODEL, verbose_name='کاربر کارفرما'),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, help_text='کد خودکار یکتا', max_length=50, unique=True, verbose_name='کد پروژه'),
        ),
        migrations.AddField(
            model_name='project',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='مشاور'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره قرارداد'),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='پیمانکار'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible_engineer',
            field=models.CharField(blank=True, max_length=200, verbose_name='مهندس مسئول'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('on_hold', 'متوقف'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ناظر'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AddField(
            model_name='sample',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='بارکد'),
        ),
        migrations.AddField(
            model_name='sample',
            name='casting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بتن\u200cریزی'),
        ),
        migrations.AddField(
            model_name='sample',
            name='code',
            field=models.CharField(blank=True, help_text='کد یکتای خودکار', max_length=50, unique=True, verbose_name='کد نمونه'),
        ),
        migrations.AddField(
            model_name='sample',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_samples', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='sample',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='محل فعلی'),
        ),
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='sample',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, verbose_name='ابعاد'),
        ),
        migrations.AddField(
            model_name='sample',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='توکن QR'),
        ),
        migrations.AddField(
            model_name='sample',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to=settings.AUTH_USER_MODEL, verbose_name='دریافت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='sample',
            name='receiving_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ دریافت در آزمایشگاه'),
        ),
        migrations.AddField(
            model_name='sample',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_samples', to=settings.AUTH_USER_MODEL, verbose_name='مهندس مسئول'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sampling_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نمونه\u200cبرداری'),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('created', 'ایجاد شده'), ('received', 'دریافت شده'), ('waiting', 'در انتظار'), ('stored', 'نگهداری'), ('curing', 'عمل\u200cآوری'), ('ready_for_test', 'آماده آزمون'), ('testing', 'در حال آزمون'), ('completed', 'تکمیل شده'), ('reported', 'گزارش شده'), ('archived', 'بایگانی'), ('cancelled', 'لغو شده')], db_index=True, default='created', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='sample',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampled_samples', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین نمونه\u200cبردار'),
        ),
        migrations.AddField(
            model_name='sample',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن (kg)'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'ایجاد'), ('update', 'بروزرسانی'), ('delete', 'حذف'), ('login', 'ورود'), ('logout', 'خروج'), ('approval', 'تأیید'), ('file_upload', 'بارگذاری فایل'), ('status_change', 'تغییر وضعیت')], max_length=30, verbose_name='عملیات')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع مدل')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='نمایش')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('project', 'پروژه'), ('sample', 'نمونه'), ('report', 'گزارش'), ('testexecution', 'اجرای آزمون'), ('labrequest', 'درخواست آزمایشگاهی'), ('equipment', 'دستگاه')], max_length=30, verbose_name='نوع پیوند')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='شناسه شیء')),
                ('file', models.FileField(upload_to='files/%Y/%m/', validators=[api.validators.validate_file_extension, api.validators.validate_file_size], verbose_name='فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری\u200cکننده')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('company', 'شرکت'), ('government', 'سازمان دولتی'), ('private', 'مشتری خصوصی')], default='private', max_length=20, verbose_name='نوع')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='شخص رابط')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('tax_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه مالیاتی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.client', verbose_name='مشتری'),
        ),
        migrations.CreateModel(
            name='CuringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='تاریخ ورود')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curing_records', to=settings.AUTH_USER_MODEL, verbose_name='اپراتور')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curing_records', to='api.sample', verbose_name='نمونه')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.curingtank', verbose_name='مخزن')),
            ],
            options={
                'verbose_name': 'رکورد عمل\u200cآوری',
                'verbose_name_plural': 'رکوردهای عمل\u200cآوری',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد دستگاه')),
                ('name', models.CharField(max_length=200, verbose_name='نام دستگاه')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='سازنده')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='مدل')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='شماره سریال')),
                ('calibration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ کالیبراسیون')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='کالیبراسیون بعدی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('maintenance', 'در تعمیر'), ('out_of_service', 'از کار افتاده'), ('retired', 'بازنشسته')], db_index=True, default='active', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'دستگاه آزمایشگاهی',
                'verbose_name_plural': 'دستگاه\u200cهای آزمایشگاهی',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='api_equipme_status_26dd77_idx'), models.Index(fields=['next_calibration_date'], name='api_equipme_next_ca_ad3b05_idx')],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کارخانه')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='تلفن کارخانه')),
                ('address', models.TextField(blank=True, verbose_name='آدرس کارخانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory', to=settings.AUTH_USER_MODEL, verbose_name='مدیر کارخانه')),
            ],
            options={
                'verbose_name': 'کارخانه بتن',
                'verbose_name_plural': 'کارخانه\u200cهای بتن',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.factory', verbose_name='کارخانه تامین بتن'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='api_project_status_89cb34_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='api_project_priorit_cf265c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='api_project_client__d2ee13_idx'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='api.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_lab_requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='api.equipment', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='profile',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.factory', verbose_name='کارخانه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.labprofile', verbose_name='آزمایشگاه'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='بازبین'),
        ),
        migrations.AddField(
            model_name='report',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='api.sample', verbose_name='نمونه'),
        ),
        migrations.AddField(
            model_name='reportrevision',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_revisions', to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده'),
        ),
        migrations.AddField(
            model_name='reportrevision',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='api.report', verbose_name='گزارش'),
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='api.sampletype', verbose_name='نوع نمونه (دسته\u200cبندی)'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status'], name='api_sample_status_6e5a42_idx'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tests', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده نتیجه'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='lab_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='api.labrequest', verbose_name='درخواست'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='api.equipment', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to=settings.AUTH_USER_MODEL, verbose_name='اپراتور'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='api.sample', verbose_name='نمونه'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_executions', to='api.testtype', verbose_name='نوع آزمون'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requested_tests',
            field=models.ManyToManyField(related_name='lab_requests', to='api.testtype', verbose_name='آزمون\u200cهای درخواستی'),
        ),
        migrations.AddField(
            model_name='acceptancecriteria',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='api.testtype', verbose_name='نوع آزمون'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='api_activit_content_25ec96_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='api_activit_action_961c51_idx'),
        ),
        migrations.AddIndex(
            model_name='appfile',
            index=models.Index(fields=['content_type', 'object_id'], name='api_appfile_content_523900_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='api_client_name_6d373d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='api_client_client__63878c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='api_notific_user_id_16328d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['project', 'status'], name='api_report_project_d33276_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['sample', 'test_type'], name='api_testexe_sample__21f305_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['status'], name='api_testexe_status_78cf48_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['result_status'], name='api_testexe_result__eafc99_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['project', 'status'], name='api_labrequ_project_ea02de_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['due_date'], name='api_labrequ_due_dat_39536a_idx'),
        ),
    ]
