# Generated by Django 5.2.16 on 2026-08-06 09:05
# Modified: data-safe migration that backfills PourSeries/StructuralMember/ProjectSettings
# from existing SamplingSeries/Mold rows.

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_structural_data(apps, schema_editor):
    """داده‌های قدیمی (SamplingSeries/Mold) را به ساختار جدید (PourSeries) منتقل می‌کند."""
    Project = apps.get_model('api', 'Project')
    Sample = apps.get_model('api', 'Sample')
    StructuralMember = apps.get_model('api', 'StructuralMember')
    PourSeries = apps.get_model('api', 'PourSeries')
    ProjectSettings = apps.get_model('api', 'ProjectSettings')
    SamplingSeries = apps.get_model('api', 'SamplingSeries')
    Mold = apps.get_model('api', 'Mold')

    # 1) یک عضو سازه‌ای پیش‌فرض برای هر پروژه + تنظیمات پیش‌فرض پروژه
    member_cache = {}
    for project in Project.objects.all():
        member, _ = StructuralMember.objects.get_or_create(
            project=project,
            name='General',
            defaults={'member_type': 'other', 'description': 'عضو سازه‌ای پیش‌فرض (مطابق با داده قدیمی)'},
        )
        member_cache[project.id] = member
        ProjectSettings.objects.get_or_create(project=project)

    # 2) برای هر سری نمونه قدیمی یک ریزش بتن می‌سازیم
    pour_cache = {}
    for series in SamplingSeries.objects.select_related('sample__project').all():
        sample = series.sample
        project = sample.project if sample else None
        member = member_cache.get(project.id) if project else None
        if member is None:
            continue
        pour, _ = PourSeries.objects.get_or_create(
            name=series.name or f'ریزش {series.id}',
            defaults={
                'pour_date': sample.casting_date or sample.date if sample else timezone.now(),
                'structural_member': member,
                'sample': sample,
                'concrete_temperature': series.concrete_temperature,
                'slump': series.slump,
                'axis': series.axis,
                'has_additive': series.has_additive,
            },
        )
        pour_cache[series.id] = pour

    # 3) قالب‌های قدیمی را به ریزش جدید وصل می‌کنیم
    for mold in Mold.objects.select_related('series').all():
        pour = pour_cache.get(mold.series_id)
        if pour is not None:
            mold.pour_series = pour
            mold.save(update_fields=['pour_series'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_catalogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuralMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام عضو سازه‌ای')),
                ('member_type', models.CharField(choices=[('foundation', 'فنداسیون'), ('column', 'ستون'), ('beam', 'تیر'), ('wall', 'دیوار'), ('slab', 'سقف'), ('stair', 'پله'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع عضو')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_members', to='api.project', verbose_name='پروژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'عضو سازه‌ای',
                'verbose_name_plural': 'اعضای سازه‌ای',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PourSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ریش بتن')),
                ('pour_date', models.DateTimeField(verbose_name='تاریخ ریش')),
                ('concrete_temperature', models.FloatField(default=0.0, verbose_name='دمای بتن')),
                ('concrete_temperature_image', models.ImageField(blank=True, null=True, upload_to='pours/concrete_temperature/', validators=[api.validators.validate_image_file], verbose_name='عکس دمای بتن')),
                ('slump', models.FloatField(default=0.0, verbose_name='اسلامپ')),
                ('slump_image', models.ImageField(blank=True, null=True, upload_to='pours/slump/', validators=[api.validators.validate_image_file], verbose_name='عکس اسلامپ')),
                ('axis', models.CharField(blank=True, max_length=100, verbose_name='محور')),
                ('has_additive', models.BooleanField(default=False, verbose_name='داشتن افزودنی')),
                ('truck_number', models.CharField(blank=True, max_length=100, verbose_name='شماره کارواز')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='شماره بچ')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('structural_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pour_series', to='api.structuralmember', verbose_name='عضو سازه‌ای')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pour_series', to='api.sample', verbose_name='نمونه')),
            ],
            options={
                'verbose_name': 'ریش بتن',
                'verbose_name_plural': 'ریش‌ها بتن',
                'ordering': ['-pour_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mold_ages', models.JSONField(blank=True, default=list, verbose_name='سن‌های پیش‌فرض قالب‌ها')),
                ('default_mold_count', models.IntegerField(default=1, verbose_name='تعداد پیش‌فرض قالب برای هر سن')),
                ('pour_name_prefix', models.CharField(default='Truck', max_length=50, verbose_name='پیشوند نام ریش')),
                ('member_name_prefix', models.CharField(default='Member', max_length=50, verbose_name='پیشوند نام عضو')),
                ('use_auto_numbering', models.BooleanField(default=True, verbose_name='استفاده خودکار از شماره‌گذاری')),
                ('next_pour_number', models.IntegerField(default=1, verbose_name='شماره بعدی ریش')),
                ('next_member_number', models.IntegerField(default=1, verbose_name='شماره بعدی عضو')),
                ('custom_age_labels', models.JSONField(blank=True, default=dict, verbose_name='نام‌های سفارشی سن قالب‌ها')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.project', verbose_name='پروژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات پروژه',
                'verbose_name_plural': 'تنظیمات پروژه‌ها',
            },
        ),
        # --- Mold: ابتدا pour_series را nullable اضافه می‌کنیم تا داده قدیمی قابل انتقال باشد ---
        migrations.AddField(
            model_name='mold',
            name='pour_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='api.pourseries', verbose_name='ریش بتن'),
        ),
        migrations.AddField(
            model_name='mold',
            name='failure_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='نوع شکست'),
        ),
        migrations.AddField(
            model_name='mold',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AddField(
            model_name='mold',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال آزمون'), ('completed', 'انجام شده'), ('rejected', 'رد شده'), ('overdue', 'دیرکرد')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='mold',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_molds', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین'),
        ),
        migrations.AddField(
            model_name='mold',
            name='test_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت آزمون'),
        ),
        # --- انتقال داده‌های قدیمی ---
        migrations.RunPython(backfill_structural_data, migrations.RunPython.noop),
        # --- حذف فیلد قدیمی series و غیرتهی کردن pour_series ---
        migrations.RemoveIndex(
            model_name='mold',
            name='api_mold_series__50e5ec_idx',
        ),
        migrations.RemoveField(
            model_name='mold',
            name='series',
        ),
        migrations.AlterField(
            model_name='mold',
            name='pour_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='api.pourseries', verbose_name='ریش بتن'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mold',
            name='age_in_days',
            field=models.IntegerField(verbose_name='سن (روز)'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='breaking_load',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='بار شکست (kg/cm2)'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='deadline',
            field=models.DateTimeField(verbose_name='موعد آزمون'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده‌های افزوده'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='mass',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='وزن (kg)'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='post_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/post_break/', validators=[api.validators.validate_image_file], verbose_name='عکس بعد شکست'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='sample_identifier',
            field=models.CharField(max_length=100, verbose_name='شناسه قالب'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_samples', to=settings.AUTH_USER_MODEL, verbose_name='مهندس مسئول'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampled_samples', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین نمونه‌برداری'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='concrete_temperature_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/concrete_temperature/', validators=[api.validators.validate_image_file], verbose_name='عکس دمای بتن'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.sample', verbose_name='نمونه'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='slump_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/slump/', validators=[api.validators.validate_image_file], verbose_name='عکس اسلامپ'),
        ),
        migrations.AlterField(
            model_name='samplingseriesphoto',
            name='image',
            field=models.ImageField(upload_to='series/specimens/', validators=[api.validators.validate_image_file], verbose_name='عکس سری نمونه‌ها'),
        ),
        migrations.AddIndex(
            model_name='samplingseries',
            index=models.Index(fields=['sample'], name='api_samplin_sample__6d40ef_idx'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['pour_series', 'age_in_days'], name='api_mold_pour_se_c9e228_idx'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['status'], name='api_mold_status_03e839_idx'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['priority'], name='api_mold_priorit_139636_idx'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['deadline'], name='api_mold_deadlin_a1cc93_idx'),
        ),
        migrations.AddIndex(
            model_name='mold',
            index=models.Index(fields=['technician'], name='api_mold_technic_514497_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsettings',
            index=models.Index(fields=['project'], name='api_project_project_6bd40e_idx'),
        ),
        migrations.AddIndex(
            model_name='structuralmember',
            index=models.Index(fields=['project', 'name'], name='api_structu_project_b0b307_idx'),
        ),
        migrations.AddIndex(
            model_name='structuralmember',
            index=models.Index(fields=['project', 'member_type'], name='api_structu_project_e7059c_idx'),
        ),
        migrations.AddIndex(
            model_name='pourseries',
            index=models.Index(fields=['structural_member', 'pour_date'], name='api_pourser_structu_b11940_idx'),
        ),
    ]
