# Generated by Django 5.2.16 on 2026-08-06 09:12

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pourseries_projectsettings_structuralmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsettings',
            options={'verbose_name': '\x062a\x0646\x0638\x06cc\x0645\x0627\x062a \x067e\x0631\x0648\x0698\x0647', 'verbose_name_plural': '\x062a\x0646\x0638\x06cc\x0645\x0627\x062a\x062a \x067e\x0631\x0648\x0698\x0647\x0647\x0627'},
        ),
        migrations.AlterModelOptions(
            name='structuralmember',
            options={'ordering': ['name'], 'verbose_name': '\x0639\x0636\x0648 \x0633\x0627\x0632\x0647\x06cc\x0627\x06cc', 'verbose_name_plural': '\x0639\x0636\x0648\x0647\x0627\x06cc \x0633\x0627\x0632\x0647\x06cc\x0627\x06cc'},
        ),
        migrations.AlterField(
            model_name='mold',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='دادههای افزوده'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='post_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/post_break/', validators=[api.validators.validate_image_file], verbose_name='عکس برد شکست'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='pour_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molds', to='api.pourseries', verbose_name='ریز بتن'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اوفویت'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال آزمون'), ('completed', 'آنجام شده'), ('rejected', 'رد شده'), ('overdue', 'دیرکولد')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_molds', to=settings.AUTH_USER_MODEL, verbose_name='تکنیسین'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='test_notes',
            field=models.TextField(blank=True, verbose_name='یادداشتت آزمون'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره بتد'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشتت'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='truck_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره کاروز'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزظا'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\x062a\x0627\x0631\x06cc\x062e \x0633\x0627\x062e\x062a'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='custom_age_labels',
            field=models.JSONField(blank=True, default=dict, verbose_name='\x0622\x0633\x0645\x0627\x06cc \x0633\x0646\x06cc \x062e\x0648\x062f\x06cc \x0633\x0645\x0638\x0632'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_mold_ages',
            field=models.JSONField(blank=True, default=list, verbose_name='\x0633\x0646\x06cc \x062e\x0648\x062f\x06cc \x0642\x0627\x0644\x0628\x0647\x06cc \x062f\x0648\x0644\x0634'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_mold_count',
            field=models.IntegerField(default=1, verbose_name='\x062a\x0634\x062f \x062e\x0648\x062f\x06cc \x0642\x0627\x0644\x0628 \x0628\x0631\x0627\x06cc \x0633\x0646'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='member_name_prefix',
            field=models.CharField(default='Member', max_length=50, verbose_name='\x067e\x06cc\x0634\x0627\x0634 \x0646\x0627\x0645 \x0639\x0636\x0648'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='next_member_number',
            field=models.IntegerField(default=1, verbose_name='\x0634\x0645\x0627\x0631\x0647 \x0628\x0639\x06cc \x0639\x0636\x0648'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='next_pour_number',
            field=models.IntegerField(default=1, verbose_name='\x0634\x0645\x0627\x0631\x0647 \x0628\x0639\x06cc \x0631\x06cc\x0634'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='pour_name_prefix',
            field=models.CharField(default='Truck', max_length=50, verbose_name='\x067e\x06cc\x0634\x0627\x0634 \x0646\x0627\x0645 \x0631\x06cc\x0634'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.project', verbose_name='\x067e\x0631\x0648\x0698\x0647'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\x0622\x062e\x0631\x06cc\x0646 \x0628\x0631\x0648\x0632\x0638\x0627'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='use_auto_numbering',
            field=models.BooleanField(default=True, verbose_name='\x0627\x0633\x062a\x0641\x0627\x062f\x0647 \x062e\x0648\x062f\x06cc \x0634\x0645\x0631\x0631\x06cc'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_samples', to=settings.AUTH_USER_MODEL, verbose_name='مهند مسئول'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampled_samples', to=settings.AUTH_USER_MODEL, verbose_name='تکنین نمونه\u200cبرداری'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\x062a\x0627\x0631\x06cc\x062e \x0633\x0627\x062e\x062a'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='description',
            field=models.TextField(blank=True, verbose_name='\x062a\x0648\x0636\x06cc\x062d\x0627\x062a\x062a'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='member_type',
            field=models.CharField(choices=[('foundation', '\x0641\x0646\x062f\x0627\x0633\x06cc\x0648\x0646'), ('column', '\x0633\x062a\x0648\x0646'), ('beam', '\x062a\x06cc\x0631'), ('wall', '\x062f\x06cc\x0648\x0627\x0631'), ('slab', '\x0633\x0642\x0641'), ('stair', '\x067e\x0644\x0647'), ('other', '\x0633\x0627\x06cc\x0631')], default='other', max_length=20, verbose_name='\x0646\x0648\x0639 \x0639\x0636\x0648'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='\x0646\x0627\x0645 \x0639\x0636\x0648 \x0633\x0627\x0632\x0647\x06cc\x0627\x06cc'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_members', to='api.project', verbose_name='\x067e\x0631\x0648\x0698\x0647'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='\x0622\x062e\x0631\x06cc\x0646 \x0628\x0631\x0648\x0632\x0631\x0638\x0627'),
        ),
    ]
