# Generated by Django 5.2.16 on 2026-08-06 12:40

import api.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_projectsettings_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pourseries',
            options={'ordering': ['-pour_date'], 'verbose_name': 'ریز بتن', 'verbose_name_plural': 'ریزهای بتن'},
        ),
        migrations.AlterModelOptions(
            name='projectsettings',
            options={'verbose_name': 'تنظیمات پروژه', 'verbose_name_plural': 'تنظیمات پروژه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='structuralmember',
            options={'ordering': ['name'], 'verbose_name': 'عضو سازه\u200cای', 'verbose_name_plural': 'اعضای سازه\u200cای'},
        ),
        migrations.RemoveIndex(
            model_name='samplingseries',
            name='api_samplin_sample__6d40ef_idx',
        ),
        migrations.AlterField(
            model_name='mold',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای افزوده'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='post_break_image',
            field=models.ImageField(blank=True, null=True, upload_to='molds/post_break/', validators=[api.validators.validate_image_file], verbose_name='عکس بعد شکست'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال آزمون'), ('completed', 'انجام شده'), ('rejected', 'رد شده'), ('overdue', 'دیرکرد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_molds', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین'),
        ),
        migrations.AlterField(
            model_name='mold',
            name='test_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت آزمون'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره بچ'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام ریز بتن'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='pour_date',
            field=models.DateTimeField(verbose_name='تاریخ ریز'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='truck_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='شماره کامیون'),
        ),
        migrations.AlterField(
            model_name='pourseries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='custom_age_labels',
            field=models.JSONField(blank=True, default=dict, verbose_name='نام\u200cهای سفارشی سن قالب\u200cها'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_mold_ages',
            field=models.JSONField(blank=True, default=list, verbose_name='سن\u200cهای پیش\u200cفرض قالب\u200cها'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='default_mold_count',
            field=models.IntegerField(default=1, verbose_name='تعداد پیش\u200cفرض قالب برای هر سن'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='member_name_prefix',
            field=models.CharField(default='Member', max_length=50, verbose_name='پیشوند نام عضو'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='next_member_number',
            field=models.IntegerField(default=1, verbose_name='شماره بعدی عضو'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='next_pour_number',
            field=models.IntegerField(default=1, verbose_name='شماره بعدی ریز'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='pour_name_prefix',
            field=models.CharField(default='Truck', max_length=50, verbose_name='پیشوند نام ریز'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='use_auto_numbering',
            field=models.BooleanField(default=True, verbose_name='استفاده خودکار از شماره\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='api.project'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='responsible_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_samples', to=settings.AUTH_USER_MODEL, verbose_name='مهندس مسئول'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sampled_samples', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین نمونه\u200cبردار'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='concrete_temperature_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/concrete_temperature/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.sample'),
        ),
        migrations.AlterField(
            model_name='samplingseries',
            name='slump_image',
            field=models.ImageField(blank=True, null=True, upload_to='series/slump/', validators=[api.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='samplingseriesphoto',
            name='image',
            field=models.ImageField(upload_to='series/specimens/', validators=[api.validators.validate_image_file], verbose_name='عکس نمونه\u200cها'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='member_type',
            field=models.CharField(choices=[('foundation', 'فنداسیون'), ('column', 'ستون'), ('beam', 'تیر'), ('wall', 'دیوار'), ('slab', 'سقف'), ('stair', 'پله'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع عضو'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام عضو سازه\u200cای'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_members', to='api.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='structuralmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
