# Generated by Django 5.2.17 on 2026-08-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_pourseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('labor', 'نیروی کار'), ('material', 'مواد و مصالح'), ('equipment', 'تجهیزات'), ('transport', 'حمل\u200cونقل'), ('testing', 'آزمایشگاهی'), ('consulting', 'مشاوره'), ('other', 'سایر')], db_index=True, default='other', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_settled',
            field=models.BooleanField(default=True, help_text='برای درآمد: وصول\u200cشده (در غیر این صورت مطالبات محسوب می\u200cشود).', verbose_name='تسویه شده'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank', 'بانکی'), ('check', 'چک')], default='bank', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', 'category', 'date'], name='api_transac_project_fddc03_idx'),
        ),
    ]
